"""add login lockout fields

Revision ID: 153bf9c5bde9
Revises: 789fa75dee04
Create Date: 2026-09-30 16:42:00.227270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153bf9c5bde9'
down_revision = '789fa75dee04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'failed_login_attempts',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.add_column(
            sa.Column(
                'locked_until',
                sa.DateTime(),
                nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
