"""Add quiz attempt limits and duration

Revision ID: 19c26ca6b17b
Revises: 72567ba4f53e
Create Date: 2026-09-30 14:36:32.710348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c26ca6b17b'
down_revision = '72567ba4f53e'
branch_labels = None
depends_on = None


def upgrade():
    # Existing quizzes need safe values for the new required fields.
    with op.batch_alter_table("quiz", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "max_attempts",
                sa.Integer(),
                nullable=False,
                server_default="1",
            )
        )

        batch_op.add_column(
            sa.Column(
                "duration_minutes",
                sa.Integer(),
                nullable=False,
                server_default="30",
            )
        )

    # Existing attempts need a valid start time.
    with op.batch_alter_table("quiz_attempt", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "started_at",
                sa.DateTime(),
                nullable=True,
            )
        )

    # Backfill existing attempts.
    op.execute(
        """
        UPDATE quiz_attempt
        SET started_at = COALESCE(attempted_at, CURRENT_TIMESTAMP)
        WHERE started_at IS NULL
        """
    )

    # Make started_at required after existing rows are populated.
    with op.batch_alter_table("quiz_attempt", schema=None) as batch_op:
        batch_op.alter_column(
            "started_at",
            existing_type=sa.DateTime(),
            nullable=False,
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.drop_column('started_at')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('max_attempts')

    # ### end Alembic commands ###
