"""add learning time tracking

Revision ID: 789fa75dee04
Revises: 19c26ca6b17b
Create Date: 2026-09-30 15:56:38.514921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789fa75dee04'
down_revision = '19c26ca6b17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=80), nullable=True),
    sa.Column('lesson_id', sa.String(length=80), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_time', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_time_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_time_learner_id'), ['learner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_time_lesson_id'), ['lesson_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_time', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_time_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_learning_time_learner_id'))
        batch_op.drop_index(batch_op.f('ix_learning_time_course_id'))

    op.drop_table('learning_time')
    # ### end Alembic commands ###
